--- drivers/soc/qcom/Makefile
+++ drivers/soc/qcom/Makefile
@@ -85,3 +85,4 @@ obj-$(CONFIG_BOOTINFO)		+= bootinfo.o
 obj-$(CONFIG_MMI_SOC_INFO) += mmi_soc_info.o
 obj-$(CONFIG_MMI_RAM_INFO) += mmi-ram-info.o
 obj-$(CONFIG_MMI_UNIT_INFO) += mmi-unit-info.o
+obj-$(CONFIG_FORCE_FAST_CHARGE) += fastchg.o
