--- drivers/char/Makefile
+++ drivers/char/Makefile
@@ -68,3 +68,4 @@ obj-$(CONFIG_MSM_ADSPRPC)       += adsprpc_compat.o
 endif
 obj-$(CONFIG_MSM_RDBG)       += rdbg.o
 obj-$(CONFIG_MSM_SMD_PKT)       += msm_smd_pkt.o
+obj-$(CONFIG_FRANDOM)	+= frandom.o
